var questions = [
   {
      question: "Which country emitted the most carbon dioxide in 2017?",
      answers: [
         "USA",
         "China",
         "Russia",
         "India"
      ],
      correctAnswer: 1,
      text: "<h2>Top Emitters</h2>China, USA, and India together emitted almost half of the total amount of emitted carbon dioxide in 2017 (Global Carbon Atlas 2017). Carbon dioxide is an important part of the atmosphere. It contributes to the greenhouse effect, which causes heat to stay on the planet. However, if the atmosphere has too much carbon dioxide, the planet will become warmer (NASA 2019). This causes glaciers and permafrost to melt, while corals and other ocean life dies because of the high amount of carbon dioxide in the water (Earth Vision Trust 2018). ",
      sources: [
         "Union of Concerned Scientists (2015). <i>CO2 Emissions</i>. Retrieved 2019-04-24 from <a href='http://www.globalcarbonatlas.org/en/CO2-emissions'>globalcarbonatlas.org</a>",
         "NASA (2019). <i>Causes</i>. Retrieved 2019-04-24 from <a href='https://climate.nasa.gov/causes' />climate.nasa.gov</a>",
         "Earth Vision Trust (2018). <i>How Carbon Dioxide Kills Ocean Life</i>. Retrieved 2019-04-24 from <a href='https://www.nationalgeographic.com/video/shorts/287287363612/'>nationalgeographic.com</a>"
      ]
   },
   {
      question: "Which of the following are greenhouse gases?",
      answers: [
         "Carbon dioxide, Methane, Nitrous oxide, Fluorinated gases",
         "Carbon dioxide, Hydrogen, Helium",
         "Carbon dioxide, Methane, Hydrogen",
         "Methane, Neon, Flourinated gases"
      ],
      correctAnswer: 0,
      text: "<h2>Greenhouse Gases</h2>According to EPA (2019), a greenhouse gas is a gas that traps heat in the atmosphere (EPA 2019). It is crucial to have a balanced amount of greenhouse gases in the atmosphere, not too much, not too little. EPA describes that carbon dioxide is by far the most emitted greenhouse gas, making up 82% of the emitted greenhouse gases in 2017. Another common greenhouse gas is methane, being emitted by different industries and even animals.",
      sources: [
         "EPA (2019). <i>Overview of Greenhouse Gases</i>. Retrieved 2019-04-24 from <a href='https://www.epa.gov/ghgemissions/overview-greenhouse-gases'>epa.gov</a>"
      ]
   },
   {
      question: "Why is it unusually cold some days, even though the earth is getting warmer?",
      answers: [
         "Climate change isn't real",
         "The sun is colder those days",
         "The earth is spinning slower those days",
         "Weather doesn’t directly correlate with climate"
      ],
      correctAnswer: 3,
      text: "<h2>Climate</h2><img src='resources/q3_img1.jpg' /><img src='resources/q3_img2.jpg' /><br />You may wonder why some days colder than usual weather, despite the earth getting warmer. Earth’s climate is warming, meaning individual days can still have colder weather while the average day is warmer than a few years ago (NASA 2019).",
      sources: [
         "NASA (2019). <i>What is Climate Change?</i> Retrieved 2019-04-24 from <a href='https://www.nasa.gov/audience/forstudents/k-4/stories/nasa-knows/what-is-climate-change-k4.html'>nasa.gov</a>"
      ]
   },
   {
      question: "Which human activities emit the most greenhouse gases?",
      answers: [
         "Transportation",
         "Agriculture",
         "Electricity &amp; Heat",
         "Industries"
      ],
      correctAnswer: 2,
      text: "<h2>Energy Sources</h2>Electricity and heat production are responsible for a quarter of all greenhouse gas emission (EPA 2017). This can be prevented by using energy generated by renewable sources.",
      sources: [
         "EPA (2017). <i>Global greenhouse gas emissions</i>. Retrieved 2019-04-24 from <a href='https://www.epa.gov/ghgemissions/global-greenhouse-gas-emissions-data#Sector'>epa.gov</a>"
      ]
   },
   {
      question: "What is the most common cause of or reason for deforestation?",
      answers: [
         "Forest fires",
         "Tree sickness",
         "Agriculture",
         "Storms"
      ],
      correctAnswer: 2,
      text: "<h2>The Importance of Forests</h2><img src='resources/q5_img1.jpg' /><img src='resources/q5_img2.jpg' /><br />Forests are extremely important, trees absorb carbon dioxide and return oxygen. This is even more important now, since it can help with absorbing the excess carbon dioxide. However, forests are being cut down in great amounts, and the biggest driver is agriculture (Persson & Henders & Kastner 2014). Another devastating side-effect of deforestation is the loss of animal and plant life’s habitat, causing imbalance in the ecosystem (Pachamama w.d).",
      sources: [
         "Persson, M & Henders, S & Kastner, T (2014). <i>Trading Forests: Quantifying the Contribution of Global Commodity Markets to Emissions from Tropical Deforestation.</i> Retrieved 2019-03-29 from <a href='https://www.cgdev.org/sites/default/files/CGD-Climate-Forest-Series-8-persson-et-al-trading-forests_0.pdf'>cgdev.org</a>",
         "Pachamama (w.d). <i>Effects of Deforestation</i> Retrieved 2019-04-29 from <a href='https://www.pachamama.org/effects-of-deforestation'>pachamama.org</a>"
      ]
   },
   {
      question: "Amur leopards are critically endangered, how many are estimated to be left?",
      answers: [
         "More than 2500",
         "More than 500",
         "More than 80",
         "More than 7500"
      ],
      correctAnswer: 2,
      text: "<h2>Amur Leopards</h2>Amur leopards live in the temperate climate of east Russia and can run 60 kilometers per hour (WWF w.d.). According to there are only about 80 known individuals left, making it a critically endangered species. Their beautiful skin has made them attractive to poachers. While poachers hunt amur leopards, they also hunt the species preys, which has given them a harder time finding food (WWF).",
      sources: [
         "WWF (w.d.) <i>Amur Leopard</i>. Retrieved 2019-05-08 from <a href='https://www.worldwildlife.org/species/amur-leopard'>worldwildlife.org</a>"
      ]
   }
];
